version: 1.0
provider:
  name: openfaas
  gateway: http://127.0.0.1:8080 # URL de l'API Gateway sur k3s

functions:
  generate-password:
    lang: python3
    handler: ./generate-password
    # registre local sur le port 5000 au lieu de Docker Hub
    image: 127.0.0.1:5000/generate-password:latest

  generate-mfa:
    lang: python3
    handler: ./generate-mfa
    image: 127.0.0.1:5000/generate-mfa:latest

  verify-mfa:
    lang: python3
    handler: ./verify-mfa
    image: 127.0.0.1:5000/verify-mfa:latest

  login:
    lang: python3
    handler: ./login
    image: 127.0.0.1:5000/login:latest
